#!/bin/bash -l
#SBATCH --job-name=modrecov
#SBATCH --nodes=1
#SBATCH --time=0-08:00:00
#SBATCH --partition general
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --output=logs/modrecov_%A_%a.out
#SBATCH --exclusive=user

# Model recovery: fit every candidate to data generated by each generator, so
# the confusion matrix says whether the comparison can identify the generating
# model at all. Forgetting models are excluded as generators until their refit
# on corrected gamma grids lands; they are still fitted as candidates.
mapfile -t MODELS < "${SLURM_SUBMIT_DIR}/BIC/_model_recovery_short.txt"
GENERATORS=()
for m in "${MODELS[@]}"; do
  [[ "$m" == *G* ]] && continue          # skip forgetting as a generator for now
  GENERATORS+=("$m")
done
NFIT=${#MODELS[@]}
GEN_IDX=$(( SLURM_ARRAY_TASK_ID / NFIT ))
FIT_IDX=$(( SLURM_ARRAY_TASK_ID % NFIT ))
GEN="${GENERATORS[$GEN_IDX]}"
FIT="${MODELS[$FIT_IDX]}"
echo "generator=${GEN}  fitted=${FIT}"

# Site specific. Apptainer may already be on PATH, or be called
# singularity, or carry a different version; do not abort if the module
# system has none of them.
module load apptainer/1.3.6 2>/dev/null || module load apptainer 2>/dev/null || true

srun apptainer exec \
    --bind "${SLURM_SUBMIT_DIR}:${SLURM_SUBMIT_DIR}" \
    --env "SIM_CONFIG_PATH=${SLURM_SUBMIT_DIR}/data/simulation_configs/simulation_params_${FIT}.py" \
    --env "GEN_TASK=${GEN}" \
    --env "SIM_ALGORITHM=de" \
    --env "SIM_N_JOBS=64" \
    --pwd "${SLURM_SUBMIT_DIR}" \
    pomdp_image.sif python3 scripts/recovery/model_recovery.py

status=$?
echo "exit=${status}"
exit ${status}
