"""Fit one candidate model to data generated by another, for model recovery.

Parameter recovery asks whether a model's parameters can be recovered from its
own simulated behavior. Model recovery asks the separate question of whether the
comparison can identify which model generated the data at all: simulate from
model G, fit every candidate, and see which one model selection actually picks.
A model can have perfectly recoverable parameters and still be indistinguishable
from a rival.

SIM_CONFIG_PATH names the model being FITTED, GEN_TASK the model that GENERATED
the data. The generated evidence is the all_simulated_data_compressed.pkl the
recovery step already writes, so nothing is simulated twice.

Usage:
    SIM_CONFIG_PATH=.../simulation_params_<FIT>.py GEN_TASK=<GEN> \
    SIM_ALGORITHM=de python model_recovery.py
"""
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from tqdm import tqdm
from tqdm_joblib import tqdm_joblib

from src.config import *  # noqa: F401,F403
from src.pomdp import POMDPFactory
from src.utils.plotting import compute_metrics_per_subject_summed as metrics_of

GEN_TASK = os.environ["GEN_TASK"]
N_JOBS = int(os.environ.get("SIM_N_JOBS", "-1"))
# MODEL_RECOVERY_GEN_ROOT / MODEL_RECOVERY_OUT_DIR let a second recovery pass
# (e.g. resampled parameters with more trials per subject) read its generators
# from a different tree and keep its cells separate, without disturbing the
# standard pass. Unset, both point at the full-likelihood tree as before.
GEN_ROOT = os.environ.get(
    "MODEL_RECOVERY_GEN_ROOT", os.path.join(PROJECT_ROOT, "data", "POMDP")
)
OUT_DIR = os.environ.get(
    "MODEL_RECOVERY_OUT_DIR", os.path.join(PROJECT_ROOT, "data", "POMDP", "_model_recovery")
)


def generated_evidence_path(gen_task):
    """Where the recovery step stored the evidence simulated from gen_task."""
    horizon = FIT_HORIZON[0] if len(FIT_HORIZON) == 1 else None
    base = os.path.join(GEN_ROOT, gen_task, ALGORITHM)
    for cand in ([os.path.join(base, horizon)] if horizon else []) + [base]:
        p = os.path.join(cand, "all_simulated_data_compressed.pkl")
        if os.path.exists(p):
            return p
    raise FileNotFoundError(
        f"no all_simulated_data_compressed.pkl for generator {gen_task} under {base}"
    )


def fit_one(evidence, subject_id):
    pomdp = POMDPFactory(POMDP_TYPE)
    best, ll, _, _, _ = pomdp.fit_subject(evidence, PARAM_RANGES, subject_id, ALGORITHM)
    return best, ll, subject_id


if __name__ == "__main__":
    src = generated_evidence_path(GEN_TASK)
    gen = pd.read_pickle(src)
    print(f"generator {GEN_TASK} -> fitting {TASK}   ({len(gen)} subjects)")

    with tqdm_joblib(tqdm(desc="subjects", total=len(gen))):
        out = Parallel(n_jobs=N_JOBS, backend="loky")(
            delayed(fit_one)(gen.loc[sid].to_dict(), sid) for sid in gen.index
        )

    df = pd.DataFrame(
        {
            "fit_params_ga": [np.array(list(b.values()), dtype=float) for b, _, _ in out],
            "after_lls_ga": [float(ll) for _, ll, _ in out],
            "subject_ID": [s for _, _, s in out],
            "data_dict_of_lists": [gen.loc[s].to_dict() for _, _, s in out],
        }
    )
    os.makedirs(OUT_DIR, exist_ok=True)
    dest = os.path.join(OUT_DIR, f"gen_{GEN_TASK}__fit_{TASK}.pkl")
    df.to_pickle(dest)
    m = metrics_of(df, "after_lls_ga")
    print(f"MODELRECOVERY {GEN_TASK} {TASK} sumLL={m['sum logL']:.2f} k={m['k']} BIC={m['BIC']:.2f}")
    print(f"wrote {dest}")
