# Generated by data/simulation_configs/generate_new_configs.py (vanilla C R1).
# Only fields that differ from src/config/schema.py's defaults are listed.
OVERRIDES = dict(
    POMDP_TYPE="vanilla",
    FIT_HORIZON=['short', 'long'],
    C_MAX=0,
    URGENCY_COEFFICIENT=0,
    URGENCY_SLOPE=0,
    PARAM_RANGES={
        "xi": (0, 1),
        "tau": (0, 100),
        "is_hazardous": (0, 1),
    },
)
