# Generated by data/simulation_configs/generate_new_configs.py (urgency C R2).
# Only fields that differ from src/config/schema.py's defaults are listed.
OVERRIDES = dict(
    POMDP_TYPE="urgency",
    FIT_HORIZON=['short', 'long'],
    PARAM_RANGES={
        "xi": (0, 1),
        "tau": (0, 100),
        "is_hazardous": (0, 1),
        "subjective_cost": (-300, 0),
        "patience": (0, 14),
        "urgency_coefficient": (-30, 0),
        "urgency_slope": (-20, 0),
        "c_max": (0, 80),
    },
)
