# Generated by data/simulation_configs/generate_new_configs.py (urgency C hazard=True).
# Only fields that differ from src/config/schema.py's defaults are listed.
OVERRIDES = dict(
    POMDP_TYPE="urgency",
    FIT_HORIZON=['short', 'long'],
    IS_HAZARDOUS=True,
    PARAM_RANGES={
        "xi": (0, 1),
        "tau": (0, 100),
        "subjective_cost": (-300, 0),
        "patience": (0, 14),
        "urgency_coefficient": (-30, 0),
        "urgency_slope": (-20, 0),
        "c_max": (0, 80),
        "belief_bias": (0.01, 5),
        "hazard_lapse": (0, 1),
    },
)
